name: Tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ['**']

  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} Test
    strategy:
      matrix:
        ruby: ['3.2', '3.3']

    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Standard compliance check
        run: bundle exec standardrb --format github
      - name: Run unit tests
        run: bundle exec rake spec
